swagger: "2.0"
info:
  title: Request Cloud Run API
  version: 1.0.0
paths:
  /publish:
    post:
      operationId: requestCloudRun
      x-google-backend:
        # このコマンドで取得したURLを指定
        # gcloud run services describe news-notification --region asia-northeast1 --format="value(status.url)"
        address: https://node-news-notification-tru3mh5nma-an.a.run.app
        jwt_audience: https://node-news-notification-tru3mh5nma-an.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              messages:
                type: array
                items:
                  type: object
                  properties:
                    data:
                      type: string
                    attributes:
                      type: object
                      additionalProperties:
                        type: string
      responses:
        "200":
          description: OK

  /unsubscribed:
    post:
      operationId: handleUnsubscribed
      x-google-backend:
        address: https://node-news-notification-tru3mh5nma-an.a.run.app
        jwt_audience: https://node-news-notification-tru3mh5nma-an.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - api_key: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              reason:
                type: string
      responses:
        "200":
          description: Unsubscribed successfully

securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header
